<div class="flex flex-col items-center justify-center">
    <x-nav-mobile2 title="Kebijakan Privasi" />
    <div class="flex flex-col h-full min-h-screen bg-gray-100 shadow-md" style="width: 414px;">
        <div class="p-4 bg-[#56B44926] bg-opacity-15 space-x-2">
            <span class="flex flex-col mb-2 font-semibold text-green-500">
                Kebijakan Privasi
            </span>
        </div>
        <div class="flex flex-col p-4">
            <span class="text-xs" style="white-space: pre-wrap;">
Kerahasian Informasi Pribadi adalah hal yang terpenting bagi yang melakukan usaha dengan nama NU CARE LAZISNU CILACAP (“Kami”). Kami berkomitmen untuk melindungi dan menghormati privasi pengguna (“Anda”) saat mengakses dan menggunakan layanan Kami termasuk namun tidak terbatas pada [lazisnucilacap.com](http://lazisnucilacap.com/) (“Layanan Kami”).Kebijakan Privasi ini mengatur landasan dasar mengenai bagaimana Kami menggunakan informasi pribadi yang Kami kumpulkan dan/atau atau Anda berikan (“Informasi Pribadi”). Kebijakan Privasi ini berlaku bagi seluruh pengguna Layanan Kami, kecuali diatur pada Kebijakan Privasi yang terpisah. Mohon membaca Kebijakan Privasi Kami dengan seksama sehingga Anda dapat memahami pendekatan dan cara Kami dalam menggunakan informasi tersebut.Kebijakan Privasi ini mencakup hal-hal sebagai berikut:

1. Informasi Pribadi yang Dapat Kami Kumpulkan
2. Penggunaan Informasi Pribadi
3. Pengungkapan Informasi Pribadi
4. Penyimpanan Informasi Pribadi
5. Hak Anda
6. Kebijakan Cookies
7. Pengakuan dan Persetujuan
8. Materi Pemasaran
9. Data Anonim
10. Keamanan Data Pribadi Anda dan Afiliasi
11. Perubahan dalam Kebijakan Privasi Kami
12. Cara Menghubungi Kami

Dengan mengunjungi dan/atau mendaftar Akun pada Layanan Kami, Anda dan/atau orang tua, wali atau pengampu Anda (jika Anda berusia dibawah 18 (delapan belas) tahun) menerima dan menyetujui pendekatan dan cara-cara yang digambarkan dalam Kebijakan Privasi ini.

A.	INFORMASI PRIBADI YANG DAPAT KAMI KUMPULKAN
Kami dapat mengumpulkan Informasi Pribadi berupa:

1. Informasi yang Anda berikan. Anda dapat memberikan informasi melalui formulir elektronik pada Layanan Kami maupun dengan berkorespondensi melalui telepon, surat elektronik, dan sebagainya. Informasi ini meliputi informasi yang Anda berikan ketika mendaftar pada Layanan Kami, berlangganan Layanan Kami, mencari produk, berpartisipasi dalam diskusi online atau fungsi media sosial lain pada Layanan Kami, mengikuti kompetisi, promosi, atau survei, serta ketika Anda melaporkan masalah dengan Layanan Kami. Informasi yang Anda berikan dapat meliputi nama, alamat, alamat surat elektronik, nomor telepon,informasi finansial dan kartu kredit, deskripsi pribadi, foto, dan data lainnya. Kami dapat meminta Anda untuk melakukan verifikasi terhadap informasi yang Anda berikan, untuk memastikan akurasi dari informasi tersebut.
2. Informasi yang Kami kumpulkan. Untuk setiap kunjungan Anda ke Layanan Kami, Kami dapat mengumpulkan informasi berikut secara otomatis:
a.	Informasi teknis, meliputi alamat Protokol Internet (IP address) yang digunakan untuk menghubungkan komputer Anda dengan internet, informasi log in Anda, jenis dan versi perambah (browser) yang digunakan, pengaturan zona waktu, jenis dan versi ekstensi perambah (browser plug-in), system operasi dan Layanan Kami;
b.	Informasi tentang kunjungan Anda, termasuk daftar lengkap Lokator Sumber Seragam (Uniform Resource Locators atau URL) yang dikunjungi menuju, melalui, dan dari Layanan Kami (termasuk tanggal dan waktu); produk yang Anda lihat atau cari; waktu respon halaman, masalah pengunduhan, lama kunjungan pada halaman tertentu, informasi interaksi pada halaman (seperti pengguliran, klik, maupun pergerakan tetikus), metode yang digunakan untuk meninggalkan situs, serta nomor telepon yang digunakan untuk menghubungi layanan pelanggan Kami.
3. Informasi yang Kami terima dari sumber lain. Kami dapat menerima informasi jika Anda menggunakan situs lain yang Kami operasikan atau layanan lain yang Kami sediakan. Kami juga bekerja sama dengan pihak ketiga (termasuk, namun tidak terbatas pada misalnya, mitra bisnis, sub-kontraktor dalam pelayanan teknis, jasa pembayaran dan pengantaran, jaringan periklanan, penyedia analisis, penyedia pencarian informasi, serta agen acuan kredit) (“Mitra Kami”) dan dapat menerima informasi dari mereka. Kami akan mengambil langkah-langkah dalam batas kewajaran untuk melakukan verifikasi terhadap informasi yang Kami dapatkan dari sumber lain sesuai dengan Peraturan yang Berlaku.

B.	PENGGUNAAN INFORMASI PRIBADI
Kami menggunakan Informasi Pribadi dengan cara-cara berikut:
Kami dapat menggunakan informasi pribadi yang dikumpulkan melalui situs Layanan kami untuk menghubungi Anda berkaitan dengan produk dan jasa yang ditawarkan oleh Kami dan/atau Mitra Kami dan sebaliknya untuk meningkatkan pengalaman Anda terhadap Kami dan/atau Mitra Kami. Informasi pribadi tidak akan dijual atau dialihkan dengan cara-cara yang melanggar peraturan perundang-undangan yang berlaku, kecuali bahwa kami akan mengungkapkan informasi yang kami kumpulkan kepada pihak pemerintah atau pihak yang berwenang lainnya jika dibutuhkan oleh hukum dan peraturan perundang-undangan yang berlaku.

C.	PENGUNGKAPAN INFORMASI PRIBADI
Kami dapat membagi atau menyingkap Data Pribadi dengan anggota kelompok usaha Kami, yang melingkupi cabang dan anak perusahaan, serta perusahaan induk utama dan anak perusahaannya. Kami dapat membagi Data Pribadi dengan pihak ketiga, termasuk:

1. Mitra bisnis, pemasok, dan sub-kontraktor dalam penyelenggaraan kontrak yang Kami laksanakan dengan mereka atau Anda.
2. Pemasang iklan dan jaringan iklan yang membutuhkan data untuk memilih dan menawarkan iklan yang relevan bagi Anda dan pengguna lain. Kami tidak membuka informasi tentang individu yang dapat diidentifikasi, namun Kami dapat menyediakan mereka informasi agregat tentang pengguna Kami (misalnya informasi bahwa 500 pria berusia di bawah 40 tahun telah mengakses tautan iklan mereka pada hari tertentu). Kami juga dapat memberikan informasi agregat untuk membantu pemasang iklan dalam menjangkau target audiens tertentu (misalnya, 50 perempuan di Jakarta Pusat). Kami dapat menggunakan data personal yang Kami kumpulkan untuk memenuhi permintaan pemasang iklan dengan menampilkan iklan mereka kepada target audiens tersebut.
3. Penyedia analisis dan mesin pencari yang membantu Kami untuk memperbaiki dan mengoptimasi Layanan Kami.
4. Kami dapat mengungkap informasi kepada pihak ketiga:
a.	Dalam situasi di mana Kami menjual atau membeli perusahaan dan/atau aset, Kami dapat menyingkap data kepada calon pembeli atau penjual dari perusahaan atau aset tersebut.
b.	Jika Kami atau perusahaan induknya atau aset-aset substansial yang terkait di dalamnya diperoleh oleh pihak ketiga, maka Data Personal yang dimiliki tentang pelanggan Kami akan menjadi salah satu aset yang dipindahtangankan.
c.	Jika Kami berada di bawah tanggung jawab untuk menyingkap atau membagi data guna mematuhi kewajiban hukum dan perjanjian lain; atau melindungi hak, harta benda, maupun keamanan dari NU CARE LAZISNU CILACAP-LAZISNU, pelanggan Kami, dan lain-lain. Hal ini mencakup penukaran informasi dengan perusahaan dan organisasi lain untuk tujuan perlindungan dari penipuan dan pengurangan risiko kredit.

D.	PENYIMPANAN INFORMASI PRIBADI
Seluruh informasi Pribadi yang Anda berikan kepada Kami disimpan di server yang aman. Semua transaksi pembayaran pada Layanan Kami akan dienkripsi. Dengan menyerahkan Informasi Pribadi Anda pada Layanan Kami, Anda menyetujui pengalihan, penyimpanan, serta pengolahan yang terjadi pada Layanan Kami. Kami akan mengambil langkah-langkah dalam batas kewajaran yang diperlukan untuk memastikan bahwa Informasi Pribadi tersebut diperlakukan dengan aman dan sesuai dengan Kebijakan Privasi serta Peraturan yang Berlaku.
Seluruh Informasi Pribadi yang Anda berikan akan Kami simpan: (i) selama Anda masih menjadi pengguna dari Layanan Kami dan (ii) setidaknya 5 (lima) tahun sejak tanggal di mana Anda berhenti menggunakan Layanan Kami; atau (iii) sesuai dengan tujuan awal dari pengumpulan Informasi Pribadi tersebut.
Dalam situasi di mana Kami memberikan (atau Anda memilih) sebuah kata sandi (password) yang mengizinkan Anda untuk mengakses bagian-bagian tertentu pada Layanan Kami, Anda bertanggung jawab untuk menjaga kerahasiaan kata sandi ini. Anda tidak diperkenankan membagi kata sandi dengan siapa pun.
Mohon untuk dapat diperhatikan bahwa transmisi informasi melalui internet tidak sepenuhnya aman. Meskipun demikian, Kami akan berusaha sebaik mungkin untuk melindungi Informasi Pribadi tersebut. Kami tidak bisa menjamin keamanan data yang dikirimkan ke Layanan Kami; risiko dari setiap transmisi menjadi tanggung jawab Anda. Begitu Kami menerima Informasi Pribadi Anda, Kami akan menggunakan prosedur yang ketat dan fitur keamanan untuk mencegah akses yang tidak diizinkan.

E.	HAK ANDA
Anda dapat memohon untuk penghapusan Informasi Pribadi Anda pada Layanan Kami atau menarik persetujuan Anda untuk setiap atau segala pengumpulan, penggunaan atau pengungkapan Informasi Pribadi Anda dengan memberikan kepada kami pemberitahuan yang wajar secara tertulis melalui detail kontak yang tercantum pada bagian J Kebijakan Privasi ini. Tergantung pada keadaan dan sifat permohonan yang Anda minta, Anda harus memahami dan mengakui bahwa setelah penarikan persetujuan atau permohonan penghapusan tersebut, Anda mungkin tidak lagi dapat menggunakan Layanan Kami. Penarikan persetujuan Anda dapat mengakibatkan penghentian Akun Anda atau hubungan kontraktual dan transaksi Anda dengan kami, dengan semua hak dan kewajiban yang muncul sepenuhnya harus dipenuhi. Setelah menerima pemberitahuan untuk menarik persetujuan untuk pengumpulan, penggunaan atau pengungkapan Informasi Pribadi Anda, Kami akan menginformasikan Anda tentang konsekuensi yang mungkin terjadi dari penarikan tersebut sehingga Anda dapat memutuskan apakah Anda tetap ingin menarik persetujuan atau tidak.
Anda dapat meminta kepada Kami untuk mengakses dan/atau mengoreksi Informasi Pribadi anda yang berada dalam kepemilikan dan penguasaan kami, dengan menghubungi kami di perincian yang disediakan di bawah ini.
Layanan Kami dapat, dari waktu ke waktu, memuat link menuju dan dari situs-situs milik jaringan Mitra, pemuat iklan, dan afiliasi lainnya. Jika Anda mengikuti link ke salah satu situs tersebut, mohon perhatikan bahwa situs-situs tersebut memiliki Kebijakan Privasi mereka sendiri dan bahwa Kami tidak bertanggung jawab atau memiliki kewajiban apa pun atas kebijakan-kebijakan tersebut. Mohon periksa kebijakan-kebijakan tersebut sebelum Anda menyerahkan informasi apapun ke situs-situs tersebut.

F.	KEBIJAKAN COOKIES
Ketika Anda menggunakan Layanan Kami, Kami dapat menempatkan sejumlah cookies pada browser Anda. Cookies adalah sebuah berkas digital kecil berisi huruf dan angka yang Kami simpan pada browser atau hard drive komputer Anda atas persetujuan Anda. Cookies mengandung informasi yang dipindahkan ke diska keras komputer Anda. Cookies dapat digunakan untuk tujuan berikut: (1) mengaktifkan fungsi tertentu, (2) memberikan analisis, (3) menyimpan preferensi Anda; dan (4) memungkinkan pengiriman iklan dan pengiklanan berdasarkan perilaku. Beberapa cookies ini hanya akan digunakan jika Anda menggunakan fitur tertentu, atau memilih preferensi tertentu, sementara sebagian Cookies lain akan selalu digunakan.Kami menggunakan cookies untuk alasan-alasan berikut:Ketika Anda menggunakan Layanan Kami, Kami dapat menempatkan sejumlah cookies pada browser Anda. Cookies adalah sebuah berkas digital kecil berisi huruf dan angka yang Kami simpan pada browser atau hard drive komputer Anda atas persetujuan Anda.
Cookies mengandung informasi yang dipindahkan ke diska keras komputer Anda.Cookies dapat digunakan untuk tujuan berikut: (1) mengaktifkan fungsi tertentu, (2) memberikan analisis, (3) menyimpan preferensi Anda; dan (4) memungkinkan pengiriman iklan dan pengiklanan berdasarkan perilaku. Beberapa cookies ini hanya akan digunakan jika Anda menggunakan fitur tertentu, atau memilih preferensi tertentu, sementara sebagian Cookies lain akan selalu digunakan.
Kami menggunakan cookies untuk alasan-alasan berikut:

1. Cookies dibutuhkan untuk pengoperasian Layanan Kami. Ini termasuk, misalnya, Cookies yang memungkinkan Anda memasuki Area yang aman di Layanan Kami, menggunakan keranjang belanja, ataupun menggunakan layanan penagihan elektronik.
2. Cookies memungkinkan Kami untuk mengenali dan menghitung jumlah pengunjung serta melihat bagaimana pengunjung bergerak di sekitar Layanan Kami saat mereka menggunakannya. Ini membantu Kami memperbaiki cara kerja Layanan Kami, misalnya, dengan memastikan pengguna menemukan apa yang mereka cari dengan mudah dan tepat.
3. Cookies digunakan untuk mengenali Anda saat kembali ke Layanan Kami. Ini memungkinkan Kami melakukan personalisasi terhadap konten Kami untuk Anda, menyapa Anda dengan nama, serta mengingat preferensi Anda (misalnya, pilihan bahasa atau wilayah Anda).
4. Cookies mencatat kunjungan Anda ke Layanan Kami, halaman yang telah Anda kunjungi, serta tautan yang telah Anda ikuti. Kami akan menggunakan informasi ini untuk membuat Layanan Kami serta iklan yang terpasang di dalamnya lebih relevan kepada minat Anda. Kami juga dapat membagi informasi ini dengan pihak ketiga untuk tujuan tersebut.
Mohon perhatikan bahwa pihak ketiga (termasuk, misalnya, jaringan periklanan dan penyedia jasa eksternal seperti jasa analisis lalu lintas web) juga dapat menggunakan Cookies ini, di mana Kami tidak memiliki kendali. Cookies ini cenderung membuat Layanan Kami dan iklan yang ditampilkan di dalamnya lebih relevan dengan minat Anda, serta meningkatkan kinerja Layanan Kami.
Anda dapat menghapus Cookies dengan cara melakukan fungsi clear data pada web browser Anda yang memungkinkan Anda untuk menolak pengaturan seluruh atau sebagian Cookies. Akan tetapi, Anda mungkin tidak dapat mengakses seluruh atau sebagian Layanan Kami.
G.	PENGAKUAN DAN PERSETUJUAN
Dengan menyetujui Kebijakan Privasi, Anda dan/atau orang tua, wali atau pengampu Anda (dalam hal Anda berusia di bawah 18 (delapan belas) tahun) mengakui bahwa Anda telah membaca dan memahami Kebijakan Privasi ini dan menyetujui segala ketentuannya. Secara khusus, Anda setuju dan memberikan persetujuan kepada kami untuk mengumpulkan, menggunakan, membagikan, mengungkapkan, menyimpan, mentransfer, atau mengolah Informasi Pribadi anda sesuai dengan Kebijakan Privasi ini.Dalam hal Anda memberikan Informasi Pribadi yang berkaitan dengan individu lain (misalnya Informasi Pribadi yang berkaitan dengan pasangan anda, anggota keluarga, teman, atau pihak lain) kepada Kami, maka Anda menyatakan dan menjamin bahwa Anda telah memperoleh persetujuan dari individu tersebut untuk, dan dengan ini menyetujui atas nama individu tersebut untuk, pengumpulan, penggunaan, pengungkapan dan pengolahan Informasi Pribadi mereka oleh Kami.
H.	MATERI PEMASARAN
Kami dan Mitra Kami dapat mengirimkan anda dan/atau orang tua, wali atau pengampu Anda pemasaran langsung, iklan, dan komunikasi promosi melalui web browser, pos, panggilan telepon, layanan pesan singkat, email dan/atau aplikasi pesan lainnya (“Materi Pemasaran”) jika Anda telah setuju untuk berlangganan milis Kami, dan/atau setuju untuk menerima materi pemasaran dan promosi dari Kami. Anda dapat memilih untuk tidak menerima komunikasi pemasaran tersebut kapan saja dengan menghubungi Kami melalui detail kontak yang tercantum pada bagian L Kebijakan Privasi ini. Mohon perhatikan bahwa jika Anda memilih untuk keluar, Kami masih dapat mengirimi Anda pesan-pesan non-promosi, seperti tanda terima atau informasi tentang Akun Anda.
I.	DATA ANONIM
Kami dapat membuat, menggunakan, melisensikan atau mengungkapkan Data Pribadi yang tersedia pada Layanan Kami, dengan catatan, (i) bahwa semua hal yang dapat mengidentifikasi telah dihapus sehingga data, baik sendiri atau dikombinasi dengan data lain yang tersedia, tidak dapat dihubungkan dengan atau dikaitkan dengan atau tidak dapat mengidentifikasi suatu individu, dan (ii) data serupa telah digabungkan sehingga data asli membentuk bagian dari kumpulan data yang lebih besar.Teknik sebagaimana disebutkan di atas juga berlaku apabila Anda melakukan (i) permintaan penghapusan akun dan Data Pribadi Anda, (ii) menarik izin penggunaan layanan dan Layanan Kami atau (iii) ketika Anda berhenti menggunakan Layanan kami. Kami akan memusnahkan setiap Data Pribadi Anda setelah 5 (lima) tahun sejak Anda melakukan salah satu dari ketiga kemungkinan tersebut, apabila Data Pribadi tidak lagi diperlukan untuk layanan atau tujuan yang disebutkan pada Kebijakan Privasi ini, serta apabila Kami tidak lagi memiliki tujuan hukum atau bisnis untuk menyimpan Data Pribadi Anda.
J.	KEAMANAN DATA PRIBADI ANDA DAN AFILIASI
Kerahasiaan Data Pribadi merupakan prioritas bagi Kami dan Afiliasi Kami. Kami akan senantiasa mengambil tindakan hukum yang layak, tindakan organisasi dan teknis yang layak untuk memastikan bahwa Data Pribadi Anda aman dan terlindungi. Setiap pemrosesan Data Pribadi Anda hanya akan dilakukan sesuai dengan Kebijakan Privasi ini dan ketentuan perundang-undangan yang berlaku.Mohon untuk dapat diperhatikan bahwa transmisi informasi melalui internet tidak sepenuhnya aman. Meskipun demikian, Kami akan berusaha sebaik mungkin untuk melindungi Data Pribadi tersebut. Kami tidak bisa menjamin keamanan data yang dikirimkan ke Layanan Kami; risiko dari setiap transmisi menjadi tanggung jawab Anda. Begitu Kami menerima Data Pribadi Anda, Kami akan menggunakan prosedur yang ketat dan fitur keamanan untuk mencegah akses yang tidak diizinkan.Anda bertanggung jawab untuk (i) menjaga kerahasiaan akun Anda, termasuk kata sandi dan rincian pembayaran, terhadap siapapun dan (ii) menjaga dan memastikan keamanan perangkat Anda yang digunakan untuk mengakses dan menggunakan Layanan.Dalam situasi dimana Kami memberikan suatu One Time Password (OTP) (atau Anda memilih) sebuah kata sandi (password) yang mengizinkan Anda untuk mengakses bagian-bagian tertentu pada Layanan Kami, Anda bertanggung jawab untuk menjaga kerahasiaan kata sandi (password) ini. Kami meminta dan menghimbau Anda untuk tidak membagi kata sandi (password) dengan siapa pun.
K.	PERUBAHAN DALAM KEBIJAKAN PRIVASI KAMI
Perubahan apa pun yang Kami lakukan terhadap Kebijakan Privasi Kami di masa depan akan diterbitkan melalui halaman ini dan, ketika dibutuhkan, diberitahukan kepada Anda melalui surat elektronik dan/atau cara-cara lainnya yang pantas. Mohon kunjungi kembali halaman ini dari waktu ke waktu untuk melihat adanya pemutakhiran atau perubahan pada Kebijakan Privasi Kami.
L.	CARA MENGHUBUNGI KAMI
Jika Anda memiliki pertanyaan mengenai Kebijakan Privasi ini atau Anda ingin mendapatkan akses dan/atau melakukan koreksi terhadap Informasi Pribadi Anda, silahkan dapat menghubungi Kami melalui Customer Service Kami di WhatsApp 082125778667.</span>
        </div>
        <div class="mb-16"></div>
    </div>
</div>
